src/WesleyBundle/Entity/Post.php
<?php
/**
 * Created by PhpStorm.
 * User: wesley
 * Date: 07-12-16
 * Time: 16:05
 */

namespace WesleyBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;
use Symfony\Component\Validator\Constraints\NotBlank;

/**
 * @ORM\Entity()
 * @ORM\HasLifecycleCallbacks()
 */
class Post
{

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var Board
     * @ORM\ManyToOne(targetEntity="WesleyBundle\Entity\Board", inversedBy="posts")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $board;

    /**
     * @var Message
     * @ORM\OneToMany(targetEntity="WesleyBundle\Entity\Message", mappedBy="post")
     */
    protected $messages;

    /**
     * @var User
     * @ORM\ManyToOne(targetEntity="WesleyBundle\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $user;

    /**
     * @var string
     * @ORM\Column(type="string")
     * @NotBlank()
     */
    protected $title;

    /**
     * @var string
     * @ORM\Column(type="text")
     * @NotBlank()
     */
    protected $content;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime")
     */
    protected $creationDate;

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {

        $this->creationDate = new \DateTime();
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->messages = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     *
     * @return Post
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set content
     *
     * @param string $content
     *
     * @return Post
     */
    public function setContent($content)
    {
        $this->content = $content;

        return $this;
    }

    /**
     * Get content
     *
     * @return string
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set creationDate
     *
     * @param \DateTime $creationDate
     *
     * @return Post
     */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
     * Get creationDate
     *
     * @return \DateTime
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Get creationDate
     *
     * @return string
     */
    public function getCreationDateTimeElapsed()
    {
        $absoluteTime = $this->creationDate->format('Y-m-d H:i:s');
        $absoluteTime = strtotime($absoluteTime);
        $cur_time = time();
        $time_elapsed = $cur_time - $absoluteTime;
        $seconds = $time_elapsed;
        $minutes = round($time_elapsed / 60);
        $hours = round($time_elapsed / 3600);
        $days = round($time_elapsed / 86400);
        $weeks = round($time_elapsed / 604800);
        $months = round($time_elapsed / 2600640);
        $years = round($time_elapsed / 31207680);
        // Seconds
        if ($seconds <= 60) {
            return "just now";
        } //Minutes
        else if ($minutes <= 60) {
            if ($minutes == 1) {
                return "one minute ago";
            } else {
                return "$minutes minutes ago";
            }
        } //Hours
        else if ($hours <= 24) {
            if ($hours == 1) {
                return "an hour ago";
            } else {
                return "$hours hrs ago";
            }
        } //Days
        else if ($days <= 7) {
            if ($days == 1) {
                return "yesterday";
            } else {
                return "$days days ago";
            }
        } //Weeks
        else if ($weeks <= 4.3) {
            if ($weeks == 1) {
                return "a week ago";
            } else {
                return "$weeks weeks ago";
            }
        } //Months
        else if ($months <= 12) {
            if ($months == 1) {
                return "a month ago";
            } else {
                return "$months months ago";
            }
        } //Years
        else {
            if ($years == 1) {
                return "one year ago";
            } else {
                return "$years years ago";
            }
        }
    }

    /**
     * Set board
     *
     * @param \WesleyBundle\Entity\Board $board
     *
     * @return Post
     */
    public function setBoard(\WesleyBundle\Entity\Board $board = null)
    {
        $this->board = $board;

        return $this;
    }

    /**
     * Get board
     *
     * @return \WesleyBundle\Entity\Board
     */
    public function getBoard()
    {
        return $this->board;
    }

    /**
     * Add message
     *
     * @param \WesleyBundle\Entity\Message $message
     *
     * @return Post
     */
    public function addMessage(\WesleyBundle\Entity\Message $message)
    {
        $this->messages[] = $message;

        return $this;
    }

    /**
     * Remove message
     *
     * @param \WesleyBundle\Entity\Message $message
     */
    public function removeMessage(\WesleyBundle\Entity\Message $message)
    {
        $this->messages->removeElement($message);
    }

    /**
     * Get messages
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getMessages()
    {
        return $this->messages;
    }

    /**
     * Set user
     *
     * @param \WesleyBundle\Entity\User $user
     *
     * @return Post
     */
    public function setUser(\WesleyBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \WesleyBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }
}

src/WesleyBundle/Resources/views/client/add_message.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}New Message{% endblock %}
{% set header_title = 'New Message' %}

{% block header_description %}
    Writing a new message for {{ post }}
{% endblock %}
{% block breadcrumb_list %}
    <li><a href="#">Forums</a></li>
    <li class="active">{{ post }}</li>
{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

src/WesleyBundle/Resources/views/client/add_post.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}New Post{% endblock %}
{% set header_title = 'New Post' %}

{% block header_description %}
    Writing a new post for {{ board }}
{% endblock %}
{% block breadcrumb_list %}
    <li><a href="#">Forums</a></li>
    <li class="active">{{ board }}</li>
{% endblock %}

{% block content %}
    {{ form(form) }}
{% endblock %}

src/WesleyBundle/Resources/views/client/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="icon" href="{{ asset('favicon.png') }}">
    <link rel="stylesheet" href="{{ asset('css/bootstrap.css') }}" media="screen">
    <link rel="stylesheet" href="{{ asset('bundles/wesley/css/font-awesome.min.css') }}"/>
    {% stylesheets "bundles/wesley/css/style.less" filter="cssrewrite" output="css/style.css" %}
    <link rel="stylesheet" href="{{ asset_url }}"/>
    {% endstylesheets %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="{% block nav_title_link %}{% endblock %}">{% block nav_title %}{% endblock %}</a>
        </div>
        <div class="collapse navbar-collapse pull-right" id="bs-example-navbar-collapse-1">
            {% if app.user %}
                <div class="navbar-text">Welkom terug, {{ app.user.username }}</div>
                <a href="{{ path('fos_user_security_logout') }}" class="btn btn-default navbar-btn">Log Out</a>
            {% else %}
                <a href="{{ path('fos_user_security_login') }}" class="btn btn-default navbar-btn">Log In</a>
                <a href="{{ path('wesley_registration_index') }}" class="btn btn-default navbar-btn">Register</a>
            {% endif %}
        </div>
</nav>
<div class="container" style="margin-top: 35px">
    <div class="page-header page-heading">
        <h1 class="pull-left">{% block header_title %}{% endblock %}</h1>
        <ol class="breadcrumb pull-right">
            {% block breadcrumb_list %}
                <li><a href="#">Forums</a></li>
                <li class="active">List of topics</li> {% endblock %}
        </ol>
        <div class="clearfix"></div>
        <div class="clearfix"></div>
    </div>

    <p class="lead">{% block header_description %}This is the right place to discuss any ideas, critics, feature requests and all the ideas regarding our website. Please follow the forum rules and always check FAQ before posting to prevent duplicate posts.{% endblock %}</p>
    {% include 'BraincraftedBootstrapBundle::flash.html.twig' with { 'close': true } %}
    {% block right_body_button %}{% endblock %}
    {% block content %}
        {% block fos_user_content %}{% endblock fos_user_content %}
    {% endblock %}
</div>

</body>
</html>

src/WesleyBundle/Resources/views/client/board.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}
    {{ board.title }}
{% endblock %}
{% block nav_title_link %}{{ path('wesley_default_index') }}{% endblock %}
{% block nav_title %}Terug naar Home{% endblock %}
{% block header_title %}{{ board.title }}{% endblock %}

{% block header_description %}
    {{ board.description }}
{% endblock %}
{% block breadcrumb_list %}
    <li><a href="{{ path('wesley_default_index') }}">Forums</a></li>
    <li class="active">{{ board.title }}</li>
{% endblock %}

{% block right_body_button %}
    <a href="{{ path('wesley_addpost_index', {'boardId': board.id}) }}" class="btn btn-default pull-right">Add Post</a>
{% endblock %}

{% block content %}
    <table class="table table-striped">
        <thead>
        <tr>
            <th class="cell-stat"></th>
            <th>
                Title
            </th>
            <th class="cell-stat text-center hidden-xs hidden-sm">Posts</th>
            <th class="cell-stat-2x hidden-xs hidden-sm">Last Post</th>
        </tr>
        </thead>
        <tbody>
        {% for post in board.posts|reverse %}
            <tr>
                <td class="text-center"><i class="fa fa-2x text-primary"></i></td>
                <td>
                    <h4>
                        <a href="{{ path('wesley_post_view', {'id': post.id, 'title': post.title}) }}">{{ post.title }}</a>
                        <small>{{ post.content }}</small>
                    </h4>
                </td>
                <td class="text-center hidden-xs hidden-sm"><a href="#">{{ post.messages.count }}</a></td>
                <td class="hidden-xs hidden-sm">by <a href="#">{{ post.user.username }}</a><br>
                    <small><i class="fa fa-clock-o"></i> {{ post.creationdatetimeelapsed }}</small>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/WesleyBundle/Resources/views/client/index.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}Home{% endblock %}
{% block nav_title %}TestForum{% endblock %}
{% block header_title %}Home{% endblock %}
{% block header_description %}Front page text of this demo forum.{% endblock %}
{% block breadcrumb_list %}
    <li class="active">Forums</li>
{% endblock %}
{% block content %}
    <table class="table forum table-striped">
        <thead>
        <tr>
            <th class="cell-stat"></th>
            <th>
                <h3>Important</h3>
            </th>
            <th class="cell-stat text-center hidden-xs hidden-sm">Topics</th>
            <th class="cell-stat text-center hidden-xs hidden-sm">Posts</th>
            <th class="cell-stat-2x hidden-xs hidden-sm">Last Post</th>
        </tr>
        </thead>
        <tbody>
        {% for board in boards %}
            <tr>
                <td class="text-center"><i class="fa fa-2x text-primary"></i></td>
                <td>
                    <h4>
                        <a href="{{ path('wesley_board_view', {'id': board.id, 'title': board.title}) }}">{{ board.title }}</a><br>
                        <small>{{ board.description }}</small>
                    </h4>
                </td>
                <td class="text-center hidden-xs hidden-sm"><a href="#">{{ board.posts.count }}</a></td>
                <td class="text-center hidden-xs hidden-sm"><a href="#">0</a></td>
                <td class="hidden-xs hidden-sm">by <a href="#">John Doe</a><br>
                    <small><i class="fa fa-clock-o"></i> 3 months ago</small>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <table class="table forum table-striped">
        <thead>
        <tr>
            <th class="cell-stat"></th>
            <th>
                <h3>Latest 5 Posts</h3>
            </th>
            <th class="cell-stat text-center hidden-xs hidden-sm">Board</th>
            <th class="cell-stat text-center hidden-xs hidden-sm">Posts</th>
            <th class="cell-stat-2x hidden-xs hidden-sm">Last Post</th>
        </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td class="text-center"><i class="fa fa-2x text-primary"></i></td>
                <td>
                    <h4>
                        <a href="{{ path('wesley_post_view', {'id': post.id, 'title': post.title}) }}">{{ post.title }}</a>
                        <small>{{ post.content }}</small>
                    </h4>
                </td>
                <td class="text-right hidden-xs hidden-sm"><a
                            href="{{ path('wesley_board_view', {'id': post.board.id, 'title': post.board.title}) }}">{{ post.board.title }}</a>
                </td>
                <td class="text-center hidden-xs hidden-sm"><a href="#">{{ post.messages.count }}</a></td>
                <td class="hidden-xs hidden-sm">by <a
                            href="{{ path('wesley_userprofile_view', {'id': post.user.id, 'username': post.user.username}) }}">{{ post.user.username }}</a><br>
                    <small><i class="fa fa-clock-o"></i> {{ post.creationdatetimeelapsed }}</small>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/WesleyBundle/Resources/views/client/message.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}

{% endblock %}

{% block header_description %}

{% endblock %}

src/WesleyBundle/Resources/views/client/post.html.twig
{% extends '@Wesley/client/base.html.twig' %}


{% block title %}
    {{ post.title }}
{% endblock %}
{% block nav_title_link %}{{ path('wesley_board_view', {'id': board_id, 'title': board}) }}{% endblock %}
{% block nav_title %}Terug naar {{ board }} board{% endblock %}
{% block header_title %}{% endblock %}

{% block header_description %}

{% endblock %}
{% block breadcrumb_list %}
    <li><a href="{{ path('wesley_default_index') }}">Forums</a></li>
    <li>
        <a href="{{ path('wesley_board_view',{'id': post.board.id, 'title': post.board.title}) }}">{{ post.board.title }}</a>
    </li>
    <li class="active">{{ post.title }}</li>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <a href="{{ path('wesley_addmessage_index', {'postId': post.id}) }}" class=" pull-right">Add Post</a>
            <h3 class="panel-title">{{ post.title }}</h3>
        </div>
        <div class="panel-body">
            {{ post.content }}
        </div>
        <div class="panel-footer">Post by: <b>{{ post.user.username }}</b>
            <div class="pull-right"><i>{{ post.creationDateTimeElapsed }}</i></div>
        </div>
    </div>


    {% for message in post.messages %}
        <div class="panel panel-default">
            {% if message.reply != null %}
                <div class="panel-heading">
                    <h3 class="panel-title">{{ message.reply.content }}</h3>
                </div>
            {% endif %}
            <div class="panel-body">
                {{ message.content }}
            </div>
            <div class="panel-footer">Message by: <b>{{ message.user.username }}</b>
                <div class="pull-right"><i>{{ message.creationDateTimeElapsed }}</i> <a
                            href="{{ path('wesley_replymessage_index',{'postId': post.id, 'replyId': message.id}) }}">Reply</a></a>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

src/WesleyBundle/Resources/views/client/profile.html.twig
{% extends '@Wesley/client/base.html.twig' %}


{% block title %}
    {{ profile.username }}
{% endblock %}
{% block nav_title_link %}{{ path('wesley_default_index') }}{% endblock %}
{% block nav_title %}Terug naar Home{% endblock %}
{% block header_title %}{% endblock %}

{% block header_description %}

{% endblock %}
{% block breadcrumb_list %}
    <li><a href="{{ path('wesley_default_index') }}">Forums</a></li>
    <li class="active">{{ profile.username }}</li>
{% endblock %}

{% block content %}
    <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">{{ profile.username }}</div>
        {% if form != null %}
            <div class="panel-body">
                {{ form(form) }}
                <h3>Current Profile Description:</h3>
                <p>{{ profile.profileDescription }}</p>
            </div>
        {% else %}
            <div class="panel-body">
                <p>{{ profile.profileDescription }}</p>
            </div>
        {% endif %}

        <!-- List group -->
        <ul class="list-group">
            <li class="list-group-item">Registration Date: {{ profile.registrationDate.format('Y-m-d H:i:s') }}</li>
            <li class="list-group-item">Amount of Posts created: {{ profile.posts.count }}</li>
            <li class="list-group-item">Amount of Messages written: {{ profile.messages.count }}</li>
        </ul>
    </div>
{% endblock %}

src/WesleyBundle/Resources/views/client/registration.html.twig
{% extends '@Wesley/client/base.html.twig' %}

{% block title %}Home{% endblock %}
{% set header_title = 'Registratie' %}
    {% block header_description %}Registreer je hier!{% endblock %}
{% block fos_user_content %}
    {{ form(form) }}
{% endblock %}